#!/bin/bash

# MAINTAINER Nicolas Vellon <nvellon@gmail.com>

sudo apt-get update
sudo apt-get install ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw logging off
sudo ufw status verbose
sudo ufw enable