#!/bin/bash

# MAINTAINER Nicolas Vellon <nvellon@gmail.com>

sudo apt-get update
sudo apt-get upgrade -y

sudo dpkg-reconfigure tzdata

sudo apt-get -y install build-essential zlib1g-dev libssl-dev libreadline6-dev libyaml-dev 
sudo apt-get -y install wget unzip curl
sudo apt-get -y install git subversion